'use strict';
// Set PLAYWRIGHT_MODULE to an existing Playwright installation if it isn't on NODE_PATH.
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { pathToFileURL } = require('node:url');

(async () => {
  const root = path.join(__dirname, '..');
  const artifacts = path.join(root, 'artifacts');
  fs.mkdirSync(artifacts, { recursive: true });
  const browser = await chromium.launch({ headless: true, channel: 'chrome' });
  const failures = [], requests = [];
  const context = await browser.newContext({ viewport: { width: 1440, height: 1100 }, offline: true, acceptDownloads: true });
  context.on('request', request => { if (/^https?:/i.test(request.url())) requests.push(request.url()); });
  const page = await context.newPage();
  page.on('pageerror', error => failures.push(error.message));
  async function renderedFonts(targetPage, selector) {
    await targetPage.evaluate(() => document.fonts.ready);
    const cdp = await context.newCDPSession(targetPage);
    await cdp.send('DOM.enable');
    await cdp.send('CSS.enable');
    const { root } = await cdp.send('DOM.getDocument');
    const { nodeId } = await cdp.send('DOM.querySelector', { nodeId: root.nodeId, selector });
    const { fonts } = await cdp.send('CSS.getPlatformFontsForNode', { nodeId });
    await cdp.detach();
    return fonts;
  }
  page.on('dialog', dialog => dialog.accept());
  await page.goto(pathToFileURL(path.join(root, 'index.html')).href);
  await page.waitForSelector('#previewArticle h2');
  assert.equal(await page.locator('#previewArticle h2').count(), 4);
  assert.equal(await page.locator('#previewArticle li').count(), 2);
  assert.match(await page.locator('#formatSummary').innerText(), /4 đề mục/);
  assert.equal(await page.evaluate(() => new Set([...document.querySelectorAll('[id]')].map(node => node.id)).size === document.querySelectorAll('[id]').length), true, 'unique DOM IDs');
  await page.screenshot({ path: path.join(artifacts, 'desktop-editor.png'), fullPage: true });

  await page.locator('#startReading').click();
  await page.waitForFunction(() => window.scrollY === 0);
  assert.equal(await page.locator('#reader').isVisible(), true);
  assert.equal(await page.locator('#tableOfContents a').count(), 4);
  await page.screenshot({ path: path.join(artifacts, 'desktop-reader.png'), fullPage: false });
  await page.locator('#tableOfContents a').last().click();
  await page.waitForFunction(() => { const top = [...document.querySelectorAll('#readerArticle h2')].at(-1).getBoundingClientRect().top; return top >= 65 && top < 250; });
  const headingTop = await page.locator('#readerArticle h2').last().evaluate(el => el.getBoundingClientRect().top);
  assert.ok(headingTop >= 65 && headingTop < 250, 'table of contents scrolls to the intended heading');
  await page.locator('#settingsButton').click();
  await page.locator('#fontSize').fill('24');
  await page.locator('[data-theme="night"]').click();
  assert.equal(await page.locator('body').getAttribute('data-theme'), 'night');
  assert.equal(await page.locator('#readerArticle').evaluate(el => getComputedStyle(el).fontSize), '24px');
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#readingSettings').isVisible(), false);
  await page.locator('#settingsButton').click();
  assert.equal(await page.locator('#fontFamily option').count(), 5);
  assert.equal(await page.locator('button[data-theme]').count(), 5);
  for (const [value, family] of [['beVietnam', 'Be Vietnam Pro'], ['manrope', 'Manrope'], ['mono', 'ui-monospace']]) {
    await page.locator('#fontFamily').selectOption(value);
    const bodyFont = await page.locator('#readerArticle p').first().evaluate(el => getComputedStyle(el).fontFamily);
    assert.ok(bodyFont.includes(family), value + ' applies to article text');
    assert.equal(await page.locator('#readerArticle h1').evaluate(el => getComputedStyle(el).fontFamily), bodyFont, 'title follows selected font');
    if (value !== 'mono') {
      const glyphFonts = await renderedFonts(page, '#readerArticle p');
      assert.ok(glyphFonts.length > 0 && glyphFonts.every(font => font.isCustomFont && font.familyName.startsWith(family)), family + ' actually renders all Vietnamese glyphs offline');
    }
  }
  await page.locator('#readingWidth').fill('480');
  assert.equal(await page.locator('#readerArticle').evaluate(el => el.getBoundingClientRect().width), 480, 'narrow width applies');
  await page.locator('#readingWidth').fill('960');
  assert.equal(await page.locator('#readerArticle').evaluate(el => el.getBoundingClientRect().width), 960, 'wide width applies');
  assert.equal(await page.locator('#readingWidthValue').innerText(), '960');
  await page.locator('[data-theme="mist"]').click();
  assert.equal(await page.locator('body').evaluate(el => getComputedStyle(el).backgroundColor), 'rgb(237, 243, 247)');
  assert.equal(await page.locator('#themeName').innerText(), 'Sương xanh');
  await page.reload();
  assert.equal(await page.locator('#fontFamily').inputValue(), 'mono', 'new font persists');
  assert.equal(await page.locator('body').getAttribute('data-theme'), 'mist', 'new theme persists');
  assert.equal(await page.locator('#readingWidth').inputValue(), '960', 'reading width persists');
  // Preferences from the previous app version migrate to the replacement fonts.
  await page.addInitScript(() => {
    if (sessionStorage.getItem('migration-fixture')) return;
    sessionStorage.setItem('migration-fixture', 'done');
    const draft = JSON.parse(localStorage.getItem('easy-text-reader-v1'));
    draft.settings.fontFamily = 'classic';
    localStorage.setItem('easy-text-reader-v1', JSON.stringify(draft));
  });
  await page.reload();
  assert.equal(await page.locator('#fontFamily').inputValue(), 'beVietnam');
  await page.locator('#readTab').click();
  await page.locator('#settingsButton').click();
  await page.locator('#fontFamily').selectOption('beVietnam');
  await page.locator('[data-theme="sepia"]').click();
  assert.equal(await page.locator('body').evaluate(el => getComputedStyle(el).backgroundColor), 'rgb(244, 233, 216)');
  await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }));
  await page.screenshot({ path: path.join(artifacts, 'desktop-settings-sepia.png') });
  await page.keyboard.press('Escape');
  const themedDownloadPromise = page.waitForEvent('download');
  await page.locator('#downloadButton').click();
  const themedDownload = await themedDownloadPromise;
  const themedPath = path.join(artifacts, 'bai-doc-sepia.html');
  await themedDownload.saveAs(themedPath);
  const themedPage = await context.newPage();
  themedPage.on('pageerror', error => failures.push(error.message));
  await themedPage.goto(pathToFileURL(themedPath).href);
  assert.equal(await themedPage.locator('body').evaluate(el => getComputedStyle(el).backgroundColor), 'rgb(244, 233, 216)', 'export retains new theme');
  assert.ok((await themedPage.locator('article p').first().evaluate(el => getComputedStyle(el).fontFamily)).includes('Be Vietnam Pro'), 'export retains new font');
  assert.ok((await renderedFonts(themedPage, 'article p')).every(font => font.isCustomFont && font.familyName === 'Be Vietnam Pro'), 'export carries the actual font, not only its name');
  assert.equal(await themedPage.locator('article').evaluate(el => el.getBoundingClientRect().width), 960, 'export retains selected width');
  assert.equal(await themedPage.locator('article p').first().evaluate(el => getComputedStyle(el).textAlign), 'justify', 'export retains justification');
  await themedPage.close();

  await page.locator('#focusButton').click();
  assert.equal(await page.locator('#readerArticle').isVisible(), true);
  for (const selector of ['.site-header', '.reader-sidebar', '.reader-tools', '#readingSettings', '#readingEnd', '.reading-progress', '#readerArticle .article-metadata']) {
    assert.equal(await page.locator(selector).isVisible(), false, selector + ' is hidden in Focus');
  }
  assert.equal(await page.locator('#exitFocusButton').isVisible(), true);
  assert.equal(await page.locator('#focusButton').getAttribute('aria-pressed'), 'true');
  assert.equal(await page.locator('#readerArticle').evaluate(el => el.getBoundingClientRect().width), 960, 'Focus respects width');
  await page.screenshot({ path: path.join(artifacts, 'desktop-focus-sepia.png') });
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('.site-header').isVisible(), true);
  assert.equal(await page.locator('#exitFocusButton').isVisible(), false);
  const readingAnchor = page.locator('#readerArticle p').nth(4);
  await readingAnchor.evaluate(el => el.scrollIntoView({ block: 'center', behavior: 'instant' }));
  const anchorBefore = await readingAnchor.evaluate(el => el.getBoundingClientRect().top);
  await page.keyboard.press('f');
  await page.waitForFunction(() => document.body.classList.contains('is-focused'));
  await page.evaluate(() => new Promise(requestAnimationFrame));
  assert.ok(Math.abs(await readingAnchor.evaluate(el => el.getBoundingClientRect().top) - anchorBefore) < 3, 'entering Focus preserves the visible paragraph');
  await page.keyboard.press('f');
  await page.evaluate(() => new Promise(requestAnimationFrame));
  assert.ok(Math.abs(await readingAnchor.evaluate(el => el.getBoundingClientRect().top) - anchorBefore) < 3, 'leaving Focus preserves the visible paragraph');
  await page.locator('#settingsButton').click();
  await page.locator('#resetSettings').click();
  assert.equal(await page.locator('#readingWidth').inputValue(), '720', 'reset restores width');
  await page.keyboard.press('Escape');
  const downloadPromise = page.waitForEvent('download');
  await page.locator('#downloadButton').click();
  const download = await downloadPromise;
  const exportedPath = path.join(artifacts, 'bai-doc-mau.html');
  await download.saveAs(exportedPath);
  const exportedPage = await context.newPage();
  await exportedPage.goto(pathToFileURL(exportedPath).href);
  assert.equal(await exportedPage.locator('h2').count(), 4);
  assert.equal(await exportedPage.locator('script[src], link[rel="stylesheet"]').count(), 0);
  await exportedPage.close();
  await page.locator('#editTab').click();
  await page.locator('#inspectToggle').check();
  const firstHeadingControl = page.locator('.inspected-block').filter({ has: page.locator('h2') }).first().locator('select');
  const blockId = await firstHeadingControl.getAttribute('data-block');
  await firstHeadingControl.selectOption('paragraph');
  assert.equal(await page.locator('#previewArticle h2').count(), 3);
  assert.ok((await page.locator('#previewArticle').innerText()).includes('1. Khi nào thì cần agent?'));
  await page.reload();
  assert.equal(await page.locator('#previewArticle h2').count(), 3, 'manual correction survives reload');
  await page.locator('#inspectToggle').check();
  await page.locator('[data-reset="' + blockId + '"]').click();
  assert.equal(await page.locator('#previewArticle h2').count(), 4);
  await page.locator('#inspectToggle').uncheck();

  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: path.join(artifacts, 'mobile-editor.png'), fullPage: true });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'mobile editor has no horizontal overflow');
  await page.locator('#readTab').click();
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: path.join(artifacts, 'mobile-reader.png'), fullPage: false });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'mobile reader has no horizontal overflow');
  await page.locator('#settingsButton').click();
  await page.locator('#fontSize').fill('28');
  assert.equal(await page.locator('#readerArticle').evaluate(el => getComputedStyle(el).fontSize), '28px', 'mobile honors the selected font size');
  await page.locator('#resetSettings').click();
  await page.keyboard.press('Escape');
  await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }));
  await page.locator('#focusButton').click();
  await page.screenshot({ path: path.join(artifacts, 'mobile-focus.png') });
  assert.equal(await page.locator('#readerArticle').isVisible(), true);
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'mobile Focus has no horizontal overflow');
  await page.locator('#exitFocusButton').click();
  assert.equal(await page.locator('.reader-tools').isVisible(), true, 'mobile exit button restores controls');
  await page.setViewportSize({ width: 320, height: 680 });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), '320px reader has no horizontal overflow');
  await page.locator('#settingsButton').click();
  const settingsBox = await page.locator('#readingSettings').boundingBox();
  assert.ok(settingsBox.x >= 0 && settingsBox.x + settingsBox.width <= 320, 'expanded settings fit 320px viewport');
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'five theme choices do not overflow');
  await page.locator('#readingWidth').fill('1040');
  assert.ok(await page.locator('#readerArticle').evaluate(el => el.getBoundingClientRect().width <= innerWidth), 'maximum width shrinks to mobile viewport');
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'wide reading setting does not cause mobile overflow');
  await page.keyboard.press('Escape');
  await page.locator('#editTab').click();
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), '320px editor has no horizontal overflow');
  await page.locator('#sourceText').fill('<img src=x onerror="window.pwned=1">\n<script>window.pwned=1</script>\nLưu ý: Giữ nguyên văn bản.');
  await page.waitForFunction(() => !document.querySelector('#saveStatus').textContent.startsWith('Tự cập nhật'));
  assert.equal(await page.locator('#previewArticle img, #previewArticle script').count(), 0);
  assert.equal(await page.evaluate(() => window.pwned), undefined);
  assert.ok((await page.locator('#previewArticle').innerText()).includes('<script>window.pwned=1</script>'));

  // A custom display title must not erase the actual title found in the input.
  await page.locator('#articleTitle').fill('Tên hiển thị khác');
  await page.locator('#sourceText').fill('# Tiêu đề gốc\n\nĐây là lời văn nguyên bản cần giữ lại.');
  await page.waitForFunction(() => !document.querySelector('#saveStatus').textContent.startsWith('Tự cập nhật'));
  assert.equal(await page.locator('#previewArticle h2').innerText(), 'Tiêu đề gốc');

  await page.locator('#sourceText').fill('# Một bài kiểm tra\n\nĐây là đoạn văn bình thường để kiểm tra căn đều hai bên. Câu cuối của đoạn không bị kéo giãn.\n\n## Một đề mục\n\n> Một đoạn trích dẫn giữ căn trái.\n\n- Một mục danh sách\n\n```\nconst a = 1;\n```\n\nMột dòng thơ\nMột dòng ngắn\nMột khoảng lặng');
  await page.waitForFunction(() => !document.querySelector('#saveStatus').textContent.startsWith('Tự cập nhật'));
  assert.equal(await page.locator('#previewArticle p:not(.verse)').first().evaluate(el => getComputedStyle(el).textAlign), 'justify');
  for (const selector of ['.verse', 'blockquote', 'li', 'pre', 'h2']) assert.equal(await page.locator('#previewArticle ' + selector).first().evaluate(el => getComputedStyle(el).textAlign), 'start', selector + ' retains natural alignment');

  const sampleText = require('fs').readFileSync(path.join(root, 'sample.txt'), 'utf8');
  await page.evaluate(text => { navigator.clipboard.readText = async () => text; }, sampleText);
  await page.locator('#pasteButton').click();
  await page.waitForFunction(() => document.querySelectorAll('#previewArticle h2').length === 4);
  await page.locator('#clearButton').click();
  assert.equal(await page.locator('#sourceText').inputValue(), '');
  assert.equal(await page.locator('#readTab').isDisabled(), true);
  await page.reload();
  assert.equal(await page.locator('#sourceText').inputValue(), '', 'cleared draft remains cleared');

  // The single-file edition works independently with networking disabled.
  const portablePage = await context.newPage();
  portablePage.on('pageerror', error => failures.push(error.message));
  await portablePage.goto(pathToFileURL(path.join(root, 'easy-text-reader-standalone.html')).href);
  await portablePage.locator('#sampleButton').click();
  assert.equal(await portablePage.locator('#previewArticle h2').count(), 4);
  assert.equal(await portablePage.locator('script[src], link[rel="stylesheet"]').count(), 0);
  await portablePage.locator('#readTab').click();
  await portablePage.locator('#settingsButton').click();
  await portablePage.locator('#fontFamily').selectOption('manrope');
  assert.ok((await renderedFonts(portablePage, '#readerArticle p')).every(font => font.isCustomFont && font.familyName.startsWith('Manrope')), 'portable app embeds real Manrope font');
  await portablePage.locator('#readingWidth').fill('880');
  await portablePage.keyboard.press('Escape');
  await portablePage.screenshot({ path: path.join(artifacts, 'desktop-manrope.png') });
  await portablePage.locator('#focusButton').click();
  assert.equal(await portablePage.locator('.site-header').isVisible(), false, 'portable Focus works');
  await portablePage.setViewportSize({ width: 390, height: 844 });
  await portablePage.screenshot({ path: path.join(artifacts, 'mobile-manrope-focus.png') });
  assert.ok(await portablePage.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'self-hosted font and width fit mobile Focus');
  await portablePage.locator('#exitFocusButton').click();
  await portablePage.locator('#homeLink').click();
  assert.ok(portablePage.url().endsWith('easy-text-reader-standalone.html'), 'standalone navigation stays inside the portable file');
  assert.deepEqual(failures, [], 'no JavaScript errors');
  assert.deepEqual(requests, [], 'no HTTP requests, even in offline mode');
  console.log('PASS: offline self-hosted fonts and Vietnamese glyphs, justification/exceptions, adjustable/persisted/exported width, font migration, five themes, Focus, desktop/mobile/320px, sample, TOC, draft, safe rendering, standalone file.');
  await browser.close();
})().catch(error => { console.error(error); process.exit(1); });
