'use strict';
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const root = path.join(__dirname, '..');
const fontRoot = path.join(root, 'assets', 'fonts');
const manifest = JSON.parse(fs.readFileSync(path.join(fontRoot, 'manifest.json'), 'utf8'));
const cssByFamily = {};
for (const font of manifest) {
  const license = fs.readFileSync(path.join(fontRoot, font.license), 'utf8');
  const faces = font.files.map(file => {
    const bytes = fs.readFileSync(path.join(fontRoot, file.file));
    if (crypto.createHash('sha256').update(bytes).digest('hex') !== file.sha256) throw new Error('Font checksum mismatch: ' + file.file);
    return '@font-face{font-family:"' + font.family + '";font-style:' + file.style + ';font-weight:' + file.weight + ';font-display:swap;src:url("data:font/woff2;base64,' + bytes.toString('base64') + '") format("woff2");}';
  }).join('\n');
  cssByFamily[font.key] = '/* ' + font.family + ' — bundled locally from Google Fonts.\n' + license + '\n*/\n' + faces;
}
// Data URLs work through file:// and let an exported reading page carry its own font.
fs.writeFileSync(path.join(root, 'fonts.js'), '/* Generated by scripts/build-fonts.cjs. Fonts and licenses are bundled; no network requests. */\nwindow.LOCAL_FONTS = ' + JSON.stringify({ cssByFamily }) + ';\n(function(){const style=document.createElement("style");style.id="localFonts";style.textContent=Object.values(window.LOCAL_FONTS.cssByFamily).join("\\n");document.head.append(style);})();\n');
console.log('Đã nhúng Be Vietnam Pro và Manrope từ các tệp WOFF2 cục bộ.');
